# Generated by Django 4.2 on 2026-02-11 13:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='method',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='transaction_id',
            field=models.CharField(default=None, editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('package_purchase', 'Package Purchase'), ('commission', 'Commission Earned')], max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000.00'))]),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved & Paid'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
