# Generated by Django 4.2.11 on 2026-04-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('investment', 'Investment'), ('package_purchase', 'Package Purchase'), ('commission', 'Commission Earned')], max_length=50),
        ),
    ]
