# Generated by Django 4.2 on 2026-02-26 11:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_transaction_options_remove_withdrawal_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('100'))]),
        ),
    ]
