# Generated by Django 4.2 on 2026-02-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatepackage',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
