# Generated by Django 4.2.11 on 2026-03-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytransaction',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
