# Generated by Django 4.2.11 on 2026-03-15 12:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0003_propertytransaction_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatepackage',
            name='generations',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='affiliatepackage',
            name='name',
            field=models.CharField(choices=[('FREE', '₦0 - No Generation'), ('BASIC', '₦25,000 - 1 Generation'), ('STANDARD', '₦50,000 - 2 Generations'), ('PREMIUM', '₦100,000 - 2 Generations'), ('PROFESSIONAL', '₦200,000 - 3 Generations'), ('ELITE', '₦500,000 - 3 Generations + Spillover')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='affiliatepackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
