# Generated by Django 4.2 on 2026-02-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0003_affiliatepackage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
