# Generated by Django 4.2 on 2026-02-10 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0004_alter_affiliate_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='affiliation.affiliatepackage'),
        ),
    ]
