# Generated by Django 4.2 on 2026-02-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0005_alter_affiliate_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
