# Generated by Django 4.2 on 2026-02-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0006_affiliate_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatepackage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
