# Generated by Django 4.2 on 2026-02-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0007_affiliatepackage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
