# Generated by Django 4.2 on 2026-02-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0009_userinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliatepackage',
            name='url',
        ),
    ]
