# Generated by Django 4.2.11 on 2026-03-03 17:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('inflow', 'Inflow (Revenue/Deposit)'), ('outflow', 'Outflow (Expense/Withdrawal)')], max_length=10)),
                ('category', models.CharField(choices=[('package', 'Package Purchase'), ('commission', 'Commission Payout'), ('referral', 'Referral Bonus'), ('salary', 'Staff Salary'), ('office', 'Office Maintenance'), ('utility', 'Utility Bills'), ('logistics', 'Logistics/Transport'), ('marketing', 'Marketing'), ('other', 'Other'), ('property_sale', 'Property Sale Inflow')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('description', models.TextField(help_text='Detailed reason for this transaction')),
                ('reference_id', models.CharField(help_text='Internal TRX or Receipt Number', max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Financial Entries',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('office', 'Office Maintenance'), ('utility', 'Utility Bills'), ('salary', 'Staff Salary'), ('logistics', 'Logistics / Transport'), ('marketing', 'Marketing'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('description', models.TextField()),
                ('receipt_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
