# Generated by Django 4.2.11 on 2026-03-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialentry',
            name='reference_id',
            field=models.CharField(help_text='Internal TRX or Receipt Number', max_length=100),
        ),
    ]
