# Generated by Django 4.2.11 on 2026-04-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_financialentry_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialentry',
            name='category',
            field=models.CharField(choices=[('package', 'Package Purchase'), ('investment', 'Investment'), ('commission', 'Commission Payout'), ('referral', 'Referral Bonus'), ('salary', 'Staff Salary'), ('office', 'Office Maintenance'), ('utility', 'Utility Bills'), ('logistics', 'Logistics/Transport'), ('marketing', 'Marketing'), ('other', 'Other'), ('property_sale', 'Property Sale Inflow')], max_length=20),
        ),
    ]
