# Generated by Django 4.2 on 2026-02-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_blacklistedip_user_user_type_user_verified_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bvn',
        ),
    ]
