# Generated by Django 4.2 on 2026-02-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofile_two_factor_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank',
            field=models.CharField(blank=True, choices=[('044-Access Bank', 'Access Bank'), ('063-Access Bank (Diamond)', 'Access Bank (Diamond)'), ('070-Fidelity Bank', 'Fidelity Bank'), ('011-First Bank of Nigeria', 'First Bank'), ('214-First City Monument Bank', 'FCMB'), ('058-Guaranty Trust Bank', 'GTB'), ('50515-Moniepoint MFB', 'Moniepoint MFB'), ('999992-OPay Digital Services Limited (OPay)', 'OPay'), ('232-Sterling Bank', 'Sterling Bank'), ('033-United Bank For Africa', 'UBA'), ('035-Wema Bank', 'Wema Bank'), ('057-Zenith Bank', 'Zenith Bank')], max_length=100, null=True),
        ),
    ]
