# Generated by Django 4.2 on 2026-02-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_userprofile_account_name_userprofile_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_login_ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
