# Generated by Django 4.2.11 on 2026-03-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_user_type_user_verified_email_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('affiliate', 'affiliate'), ('investor', 'investor'), ('admin', 'admin'), ('manager', 'manager'), ('secretary', 'secretary')], default='affiliate', max_length=25),
        ),
    ]
