# Generated by Django 4.2 on 2026-02-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_userprofile_address_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('affiliate', 'affiliate'), ('admin', 'admin'), ('manager', 'manager'), ('secretary', 'secretary')], default='affiliate', max_length=25),
        ),
    ]
