# Generated by Django 4.2 on 2026-02-08 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('REGISTER', 'User Registration'), ('PASSWORD_CHANGE', 'Password Change'), ('COMMISSION_CREATE', 'Commission Created'), ('COMMISSION_PAY', 'Commission Paid'), ('TRANSACTION_CREATE', 'Transaction Created'), ('PROFILE_UPDATE', 'Profile Update'), ('SUSPICIOUS', 'Suspicious Activity'), ('API_ACCESS', 'API Access')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['-timestamp'], name='security_se_timesta_8b2c21_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['user', '-timestamp'], name='security_se_user_id_84c0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['severity', '-timestamp'], name='security_se_severit_2dcf38_idx'),
        ),
    ]
