# Generated by Django 4.2.11 on 2026-03-31 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('professional', 'Professional')], max_length=20, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Null means no upper limit', max_digits=15, null=True)),
                ('duration_months', models.PositiveIntegerField()),
                ('payout_frequency_months', models.PositiveIntegerField(help_text='Months between payouts (e.g., 4 for every 4 months)')),
                ('total_payouts', models.PositiveIntegerField(help_text='Total number of payouts over the duration')),
                ('roi_percentage', models.DecimalField(decimal_places=2, help_text='Annual ROI percentage', max_digits=5)),
                ('is_annual_roi', models.BooleanField(default=False, help_text='Is the ROI calculated annually?')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investment Plan',
                'verbose_name_plural': 'Investment Plans',
                'ordering': ['display_order', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('payout_scheduled', 'Payout Scheduled'), ('payout_completed', 'Payout Completed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('investment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('maturity_date', models.DateTimeField(blank=True, null=True)),
                ('total_expected_return', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_paid_out', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payouts_completed', models.PositiveIntegerField(default=0)),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='investments/payment_proofs/%Y/%m/')),
                ('payment_verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_investments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='base.investmentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_number', models.PositiveIntegerField()),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('return_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('scheduled_date', models.DateTimeField()),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='investments/payout_receipts/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='base.investment')),
            ],
            options={
                'ordering': ['investment', 'payout_number'],
                'unique_together': {('investment', 'payout_number')},
            },
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'status'], name='base_invest_user_id_dcd8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['status', 'maturity_date'], name='base_invest_status_75ebbf_idx'),
        ),
    ]
