# Generated by Django 4.2.11 on 2026-04-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
