# Generated by Django 4.2.11 on 2026-04-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_investment_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='payout_frequency_months',
            field=models.PositiveIntegerField(help_text='Months between payouts (e.g., 4 for every 4 months or 3 for every 3 months)'),
        ),
    ]
